//! Emits the accessor source and the unused-Message report.

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use crate::error::Result;
use crate::extract::Kind;
use crate::layer::{Item, Layer, snake};

/// What to generate, and where.
#[derive(Debug, Clone)]
pub struct Options {
    /// The layer's `i18n` directory, holding `<locale>/*.ftl`.
    pub i18n_dir: PathBuf,

    /// Where the generated Rust source is written (normally `$OUT_DIR/msg.rs`).
    pub out_file: PathBuf,

    /// The path to the runtime module, e.g. `crate::runtime` or `::lib_locale::runtime`.
    pub runtime_path: String,

    /// The prefix every id must carry (`desktop-`, `tui-`), or `None` for the shared layer,
    /// which must not use a bin prefix.
    pub id_prefix: Option<String>,

    /// Source directories scanned for unused Messages. Empty skips the report.
    pub scan_dirs: Vec<PathBuf>,
}

/// The result of [`generate`], without any file or `cargo` side effects.
#[derive(Debug)]
pub struct Generated {
    /// The generated Rust source.
    pub code: String,

    /// Every Catalogue file and directory read, for `cargo::rerun-if-changed`.
    pub watched: Vec<PathBuf>,

    /// Accessor names no scanned source calls.
    pub unused: Vec<String>,
}

/// Runs the checks and generates the source, without writing anything.
pub fn generate(options: &Options) -> Result<Generated> {
    let layer = Layer::load(&options.i18n_dir, options.id_prefix.as_deref())?;

    let mut watched = vec![options.i18n_dir.clone()];
    for (locale, files) in &layer.locales {
        watched.push(options.i18n_dir.join(locale));
        watched.extend(files.files.iter().map(|file| file.path.clone()));
    }

    let runtime = &options.runtime_path;
    let mut code = String::from("// @generated by lib_locale_build. Do not edit.\n\n");

    code.push_str(&format!("pub const LAYER: {runtime}::Layer = &[\n"));
    for (locale, files) in &layer.locales {
        let _ = writeln!(code, "    ({locale:?}, &[");
        for file in &files.files {
            let absolute = fs::canonicalize(&file.path)?;
            let _ = writeln!(
                code,
                "        ({:?}, include_str!({:?})),",
                file.name,
                absolute.to_string_lossy()
            );
        }
        code.push_str("    ]),\n");
    }
    code.push_str("];\n");

    let mut names = Vec::new();
    if let Some(source) = layer.source() {
        for item in source.items.values() {
            code.push_str(&accessor(item, runtime));
            names.push(item.accessor());
        }
    }

    let unused = if options.scan_dirs.is_empty() {
        Vec::new()
    } else {
        let haystack = read_sources(&options.scan_dirs)?;
        names
            .into_iter()
            .filter(|name| !is_called(&haystack, name))
            .collect()
    };

    Ok(Generated {
        code,
        watched,
        unused,
    })
}

/// Generates, writes the output file and prints the `cargo::` directives a `build.rs` needs.
pub fn run(options: &Options) -> Result<()> {
    let generated = generate(options)?;
    fs::write(&options.out_file, &generated.code)?;
    for path in &generated.watched {
        println!("cargo::rerun-if-changed={}", path.display());
    }
    for name in &generated.unused {
        println!("cargo::warning=unused Message accessor `{name}`");
    }
    Ok(())
}

fn accessor(item: &Item, runtime: &str) -> String {
    let params: Vec<String> = item
        .params
        .iter()
        .map(|(name, kind)| {
            let ty = match kind {
                Kind::Number => "i64",
                Kind::Text => "&str",
            };
            format!("{}: {ty}", snake(name))
        })
        .collect();
    let args: Vec<String> = item
        .params
        .iter()
        .map(|(name, kind)| {
            let variant = match kind {
                Kind::Number => "Int",
                Kind::Text => "Text",
            };
            format!("({name:?}, {runtime}::Arg::{variant}({}))", snake(name))
        })
        .collect();
    let attribute = match &item.attribute {
        Some(attribute) => format!("Some({attribute:?})"),
        None => "None".to_string(),
    };
    let (returns, call) = if item.rich {
        (format!("Vec<{runtime}::Segment>"), "format_rich")
    } else {
        ("String".to_string(), "format")
    };
    format!(
        "\n/// The `{id}` Message{attr}.\npub fn {name}({params}) -> {returns} {{\n    {runtime}::{call}({id:?}, {attribute}, &[{args}])\n}}\n",
        id = item.id,
        attr = item
            .attribute
            .as_ref()
            .map(|a| format!(" (attribute `{a}`)"))
            .unwrap_or_default(),
        name = item.accessor(),
        params = params.join(", "),
        args = args.join(", "),
    )
}

fn read_sources(dirs: &[PathBuf]) -> Result<String> {
    let mut all = String::new();
    for dir in dirs {
        read_dir_sources(dir, &mut all)?;
    }
    Ok(all)
}

fn read_dir_sources(dir: &Path, all: &mut String) -> Result<()> {
    for entry in fs::read_dir(dir)? {
        let path = entry?.path();
        if path.is_dir() {
            read_dir_sources(&path, all)?;
        } else if path.extension().is_some_and(|extension| extension == "rs") {
            all.push_str(&fs::read_to_string(&path)?);
            all.push('\n');
        }
    }
    Ok(())
}

fn is_called(haystack: &str, name: &str) -> bool {
    let call = format!("{name}(");
    haystack.match_indices(&call).any(|(at, _)| {
        !haystack[..at]
            .chars()
            .next_back()
            .is_some_and(|before| before.is_alphanumeric() || before == '_')
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    fn options(dir: &Path, prefix: Option<&str>) -> Options {
        Options {
            i18n_dir: dir.join("i18n"),
            out_file: dir.join("msg.rs"),
            runtime_path: "crate::runtime".to_string(),
            id_prefix: prefix.map(str::to_string),
            scan_dirs: Vec::new(),
        }
    }

    fn write(dir: &Path, locale: &str, file: &str, body: &str) {
        let locale_dir = dir.join("i18n").join(locale);
        fs::create_dir_all(&locale_dir).unwrap();
        fs::write(locale_dir.join(file), body).unwrap();
    }

    fn failure(options: &Options) -> String {
        generate(options).unwrap_err().to_string()
    }

    #[test]
    fn generates_typed_accessors() {
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "en-US",
            "accounts.ftl",
            "accounts-add-submit = Add account\n\
             accounts-delete =\n    .title = Delete { $count ->\n        [one] { $count } account\n       *[other] { $count } accounts\n    }?\n    .body = Delete { $name }?\n",
        );
        let generated = generate(&options(dir.path(), None)).unwrap();
        assert!(
            generated
                .code
                .contains("pub fn accounts_add_submit() -> String")
        );
        assert!(
            generated
                .code
                .contains("pub fn accounts_delete_title(count: i64) -> String")
        );
        assert!(
            generated
                .code
                .contains("pub fn accounts_delete_body(name: &str) -> String")
        );
        assert!(!generated.code.contains("unwrap"));
        assert!(!generated.code.contains("expect"));
    }

    #[test]
    fn sparse_locale_may_hold_only_overrides() {
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "en-US",
            "a.ftl",
            "colour-label = Pick a color\nother = Other\n",
        );
        write(
            dir.path(),
            "en-GB",
            "a.ftl",
            "colour-label = Pick a colour\n",
        );
        assert!(generate(&options(dir.path(), None)).is_ok());
    }

    #[test]
    fn rejects_id_missing_from_source() {
        let dir = tempfile::tempdir().unwrap();
        write(dir.path(), "en-US", "a.ftl", "one = One\n");
        write(dir.path(), "en-GB", "a.ftl", "two = Two\n");
        assert!(failure(&options(dir.path(), None)).contains("`two` is not in en-US"));
    }

    #[test]
    fn rejects_mismatched_variables() {
        let dir = tempfile::tempdir().unwrap();
        write(dir.path(), "en-US", "a.ftl", "greet = Hello { $name }\n");
        write(dir.path(), "en-GB", "a.ftl", "greet = Hello { $who }\n");
        assert!(failure(&options(dir.path(), None)).contains("variables differ"));
    }

    #[test]
    fn rejects_accessor_collisions() {
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "en-US",
            "a.ftl",
            "accounts-delete =\n    .title = A\naccounts-delete-title = B\n",
        );
        assert!(failure(&options(dir.path(), None)).contains("both give the accessor"));
    }

    #[test]
    fn enforces_id_prefix_rules() {
        let dir = tempfile::tempdir().unwrap();
        write(dir.path(), "en-US", "a.ftl", "tui-hint = Hint\n");
        assert!(failure(&options(dir.path(), None)).contains("bin-only prefix"));
        assert!(generate(&options(dir.path(), Some("tui-"))).is_ok());
        assert!(failure(&options(dir.path(), Some("desktop-"))).contains("must start with"));
    }

    #[test]
    fn rejects_pseudo_locale_files_and_missing_source() {
        let dir = tempfile::tempdir().unwrap();
        write(dir.path(), "en-XA", "a.ftl", "one = One\n");
        let message = failure(&options(dir.path(), None));
        assert!(message.contains("en-XA is generated"));
        assert!(message.contains("missing the source Locale"));
    }

    #[test]
    fn unresolved_references_do_not_fail() {
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "en-US",
            "a.ftl",
            "tui-x = { -shared-term } and { shared-message }\n",
        );
        assert!(generate(&options(dir.path(), Some("tui-"))).is_ok());
    }

    #[test]
    fn reports_unused_accessors() {
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "en-US",
            "a.ftl",
            "used-one = A\nunused-one = B\n",
        );
        let src = dir.path().join("src");
        fs::create_dir_all(&src).unwrap();
        fs::write(src.join("main.rs"), "fn main() { msg::used_one(); }").unwrap();
        let mut options = options(dir.path(), None);
        options.scan_dirs = vec![src];
        assert_eq!(
            generate(&options).unwrap().unused,
            vec!["unused_one".to_string()]
        );
    }

    #[test]
    fn messages_with_tags_or_the_rich_comment_return_segments() {
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "en-US",
            "a.ftl",
            "tui-open = Press <open>open</open> to see { $key }\n\
             # @rich\n\
             tui-key = Press { $key } to continue\n\
             tui-plain = Nothing special\n",
        );
        let code = generate(&options(dir.path(), Some("tui-"))).unwrap().code;
        assert!(code.contains("pub fn tui_open(key: &str) -> Vec<crate::runtime::Segment>"));
        assert!(code.contains("crate::runtime::format_rich(\"tui-open\""));
        assert!(code.contains("pub fn tui_key(key: &str) -> Vec<crate::runtime::Segment>"));
        assert!(code.contains("pub fn tui_plain() -> String"));
    }

    #[test]
    fn tags_must_match_the_source_locale() {
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "en-US",
            "a.ftl",
            "tui-open = Press <open>open</open>\n",
        );
        write(
            dir.path(),
            "en-GB",
            "a.ftl",
            "tui-open = Press <close>open</close>\n",
        );
        assert!(failure(&options(dir.path(), Some("tui-"))).contains("uses tags"));
        write(dir.path(), "en-GB", "a.ftl", "tui-open = Press open\n");
        assert!(failure(&options(dir.path(), Some("tui-"))).contains("uses tags"));
        write(
            dir.path(),
            "en-GB",
            "a.ftl",
            "tui-open = Push <open>open</open>\n",
        );
        assert!(generate(&options(dir.path(), Some("tui-"))).is_ok());
    }

    #[test]
    fn unbalanced_tags_fail_but_other_angle_brackets_are_literal() {
        let dir = tempfile::tempdir().unwrap();
        write(dir.path(), "en-US", "a.ftl", "tui-a = Press <open>open\n");
        assert!(failure(&options(dir.path(), Some("tui-"))).contains("never closed"));
        write(dir.path(), "en-US", "a.ftl", "tui-a = Press open</open>\n");
        assert!(failure(&options(dir.path(), Some("tui-"))).contains("not open"));
        write(
            dir.path(),
            "en-US",
            "a.ftl",
            "tui-a = a < b and c > d, <3 and <Upper>\n",
        );
        let code = generate(&options(dir.path(), Some("tui-"))).unwrap().code;
        assert!(code.contains("pub fn tui_a() -> String"));
    }

    #[test]
    fn tags_balance_across_placeables() {
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "en-US",
            "a.ftl",
            "tui-a = Press <key>{ $key }</key> now\n",
        );
        let code = generate(&options(dir.path(), Some("tui-"))).unwrap().code;
        assert!(code.contains("Vec<crate::runtime::Segment>"));
    }
}
