//! # Payee Aliases Database Model
//!
//! Defines the `PayeeAliases` struct, one row of the `payee_aliases` table — a Payee's
//! former name, preserved automatically by [`crate::Payees::rename`] so a suggestion typed
//! against the old name still resolves to the renamed Payee (see `CONTEXT.md`'s Payee Alias
//! entry, [ADR-0012](../../../../../docs/adr/0012-payee-entity-with-rename-aliases.md)).
//! Write-once: a row is only ever inserted by a rename, never updated or deleted in V1, so
//! there is deliberately no `update`/`delete` here.

/// Database row model representing one persisted Payee Alias.
#[derive(Debug, sqlx::FromRow, serde::Deserialize, serde::Serialize, PartialEq, Clone)]
pub struct PayeeAliases {
    /// Unique time-ordered identifier for the Payee Alias — its UUIDv7 stands in for when
    /// the rename happened, since this row is write-once (see module docs).
    pub id: lib_core::RowID,

    /// The Payee this alias resolves to.
    pub payee_id: lib_core::RowID,

    /// A regex matched against typed Payee text to resolve it to `payee_id`. In V1 this is
    /// always auto-generated by [`crate::Payees::rename`] as a case-insensitive, anchored
    /// exact match on the prior name — never hand-authored.
    pub pattern: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn payee_aliases_struct_derives_work() {
        let a = PayeeAliases {
            id: lib_core::RowID::new(),
            payee_id: lib_core::RowID::new(),
            pattern: "(?i)^Kmart$".to_string(),
        };
        let b = a.clone();
        assert_eq!(a, b);

        let debug_str = format!("{:?}", a);
        assert!(debug_str.contains("PayeeAliases"));

        let json = serde_json::to_string(&a).unwrap();
        let deserialized: PayeeAliases = serde_json::from_str(&json).unwrap();
        assert_eq!(a, deserialized);
    }
}
